cloudflare/cloudflare-rs

src/endpoint.rs
src/lib.rs

Allows endpoints to configure `"Content-Type"` header. Defaults to `"application/json"`. Blocker for work on https://github.com/cloudflare/wrangler/pull/405.

fix #10: add content-type method to Endpoint

---

src/endpoints/workerskv/mod.rs
src/endpoints/workerskv/write_bulk.rs

This PR adds support for the Workers KV bulk upload API endpoint: https://api.cloudflare.com/#workers-kv-namespace-write-multiple-key-value-pairs.
It is used by https://github.com/cloudflare/wrangler/pull/445

Add support for Workers KV bulk upload API endpoint

---

src/endpoints/workerskv/mod.rs

This is a small bug fix; the KV API returns i64 values for time, not UTC timestamps. Would love to get this in before we release our upcoming cloudflare-rs version.

Need to parse KV API times as i64

---

src/endpoints/workerskv/list_namespaces.rs

Previously, these params were actually not usable because they were not accepted as part of the request.

Ensure KV List params are passed into KV namespace list endpoint

---

.github/workflows/publish.yml

This PR introduces a GitHub action that automatically publishes cloudflare-rs to crates.io when we create a release: https://help.github.com/en/articles/creating-releases

Basic publish impl for Cargo publish

---

.github/workflows/rust.yml

This might fix the problem I'm having in trying to get CI to build code that requires Rust 1.39

CI should use latest stable rust

---

.github/workflows/rust.yml

@ashleygwilliams suggested our CI should copy from https://github.com/hecrj/setup-rust-action and I Have Obeyed The Wisdom Received.

CI can test multiple os/rust versions

---

src/framework/response/mod.rs

fix#70: use invalid url to test failure equality

---

CONTRIBUTING.md
Cargo.toml
e2e_tests/main.rs
src/endpoints/load_balancing/mod.rs
src/framework/apiclient.rs
src/framework/async_api.rs
src/framework/auth.rs
src/framework/mod.rs
src/framework/reqwest_adaptors.rs
src/framework/response/mod.rs
src/lib.rs

Features:
- an async API client under `framework::async_api::Client` that works just like `framework::apiclient::ApiClient`, except there's no trait for it (because there's no async fn in traits yet)
- e2e tests updated to use the async client, to prove it works.
- updated some other dependencies
Future work:
You'll notice that `framework/async_api.rs` has some repeated code from `framework/mod.rs` Unfortunately, `reqwest::{request, client, response}` and `reqwest::blocking::{request, client, response}` don't share any traits, so it's not clear how best to share code across the a/sync implementations. I've factored out as much as I can with plain old functions. Please let me know if you have any suggestions for making the code more DRY!

Fix #61, 63: async API client

---

.github/workflows/publish.yml

When I did #77 the project structure changed. I forgot to update the release.yml script to use the new project structure.

Update publish.yml to use new cargo workspace

---

cloudflare/Cargo.toml

No changes, but the release script was broken when I released 0.6.0

Release 0.6.1

---

cloudflare-e2e-test/src/main.rs
cloudflare/Cargo.toml
cloudflare/src/framework/apiclient.rs
cloudflare/src/framework/async_api.rs
cloudflare/src/framework/mock.rs

This PR
- Adds an async API trait
- Makes the async API client impl it
- Makes the mock API client impl it
- Updates the e2e tests, to demonstrate that functions can take the async API trait as a parameter (instead of the async API client).
Note this adds a slight bit of overhead for using the async client, because of `dyn`, which has to box the concrete type and put it on the heap (I think). But that's going to be dominated by the cost of the network calls and possibly the serializing/deserializing JSON

Trait for async API clients

---

cloudflare/Cargo.toml

- Bump http from 0.1 to 0.2
- Change dependencies like `foo = x.y.z` to `foo = x.y` because the consumers of a library should be choosing which exact versions to use.

Bump dependencies

---

cloudflare/src/framework/async_api.rs
cloudflare/src/framework/mod.rs

Allows users to set default headers for their HTTP calls.

Customize client's default headers

---

cloudflare/src/endpoints/workers/create_secret.rs
cloudflare/src/endpoints/workers/delete_secret.rs
cloudflare/src/endpoints/workers/list_secrets.rs
cloudflare/src/endpoints/workers/mod.rs

Addition of the future Workers secret API endpoint

Secrets endpoints

---

cloudflare/src/endpoints/workers/delete_tail.rs

the api returns an empty result body. this has been tested locally with  wrangler tail.

correct Workers DELETE /tail endpoint return type

---

cloudflare/src/endpoints/zone.rs

`development_mode` is a timestamp that can be negative therefore use a signed int.
32 bits may or may not be enough to represent the time range.

Fix development_mode type in Zone struct

---

cloudflare/src/endpoints/zone.rs

According to the zone Object definition here: https://api.cloudflare.com/#zone-properties

vanity_name_servers is no longer in the Zone object

---

cloudflare/src/endpoints/zone.rs

The ListZonesParams way not being passed
in the ListZones struct or used in the endpoint trait.

Endpoints: Actually use the ListZonesParams

---

cloudflare/src/endpoints/account/mod.rs
cloudflare/src/endpoints/zone.rs

When querying the list zones api "GET zones" https://api.cloudflare.com/#zone-list-zones
The account details returned only contain the `id` and the `name` fields therefore create placeholder defaults for the remaining fields in the `Account` struct.

add default for account struct

---

cloudflare/src/endpoints/plan.rs

The `frequency` field is empty when on the free plan.

Handle getting an empty frequency field for Free Plan

---

README.md
cloudflare/Cargo.toml
cloudflare/src/framework/async_api.rs
cloudflare/src/framework/auth.rs
cloudflare/src/framework/blocking_api.rs
cloudflare/src/framework/mod.rs
cloudflare/src/framework/response/mod.rs

Using the cloudflare in a wasm32 target was failing to compile.
The first reason being that the blocking client cannot ever work
in wasm.
The second reason being that the asynchronous client was using
the async_trait that did not work fine under wasm_bindgen either.
As a result, we now hide away those portions of the framework
implementation when targeting wasm32. We do so by resorting to
conditional compilation macros.
To test this out we used the framework to call some endpoints in
a Cloudflare Worker written in Rust (thus running in wasm) and it
all worked fine after these changes.
This thus enables Workers' developers in Rust to use this library
at will and contribute further to it.

Make cloudflare crate usable in wasm32 targets

---

cloudflare-e2e-test/Cargo.toml
cloudflare/Cargo.toml

Now that tokio 1.0 got released and most of the ecosystem has migrated to it, would be great to have this crate support it as well to avoid having to run tokio compatibility crates or multiple runtimes in one app.

Upgrade to tokio 1.0

---

.github/workflows/rust.yml
cloudflare/src/framework/json_utils.rs

Also enables github action test runs on pull requests

(fix master) Use Result from std instead of serde's undocumented now private re-export

---

cloudflare/Cargo.toml

Enable rustls in reqwest with 
`cloudflare = { version = "0.7", default-features = false, features = ["rustls-tls"] }`

Add rustls-tls feature to use rustls with reqwest

---

cloudflare/src/endpoints/workers/create_tail.rs

There's now a V2 implementation of tail that doesn't involve an external URL, so that param should be optional. The API respects an empty body, an empty JSON object body, and no body, so whatever I managed to do here should be fine. If I understand correctly, the way I've written this will omit the body entirely.

Update tail endpoint

---

cloudflare/src/endpoints/workers/mod.rs

When you don't submit a URL to the API, it doesn't give you an API back.
Updating from `String` to `Option<String>` prevents `cloudflare-rs` from
failing when serde fails to deserialize the response -- it's expecting a
url, but there isn't one.

Fix tail v2 requests

---

cloudflare/Cargo.toml
cloudflare/src/endpoints/user.rs

In response to a recent upstream change within the public API, the Wrangler client is seeing some errors, e.g. https://github.com/cloudflare/wrangler/issues/1914
This PR provides a default to the `betas` field which now may likely be empty (and omitted from the API response) in many more cases. The attribute added here is done so that we are not forcing a change on users of this crate to otherwise handle an `Option<Vec<String>>`, but rather encounter an empty vec if `betas` is not present in the json response.

fix: handle possible missing betas field from user details response

---

cloudflare/Cargo.toml

There's a bug in reqwest 0.11.0 which breaks usage in workers (https://github.com/seanmonstar/reqwest/issues/1247)

Upgrade reqwest to 0.11.3 for workers wasm support

---

cloudflare/src/framework/auth.rs

This PR fixes an error I encountered:
```
the trait bound `Environment: Clone` is not satisfied
```
because one of its members (Credentials) doesn't implement Clone.

feat: derive clone on credentials

---

cloudflare/Cargo.toml

Prep for new tag and release of `v0.8.7` to crates.io

meta: bump cargo version to 0.8.7

---

cloudflare/src/endpoints/mod.rs
cloudflare/src/endpoints/r2.rs

keeping endpoints in 1 file for now, for simplicity.

feat: add r2 endpoints (#170)

---

cloudflare/Cargo.toml

We don't use these slog dependencies anywhere. Let's pull them out.

deps: remove unused slog dependencies

---

cloudflare/Cargo.toml

This reverts commit 2793ff07a3cd420856c315b67188bc694a31e818.
The release was not tagged correctly, so we'll do revert the commit so we can do it again.

Revert "Release 0.9.1 (#180)"

---

cloudflare/Cargo.toml
cloudflare/src/framework/async_api.rs
cloudflare/src/framework/blocking_api.rs
cloudflare/src/framework/mod.rs

This adds an optional field to HttpApiClientConfig that lets you specify a pre-resolved IP address for the API.

Add resolver IP to HttpApiClientConfig

---

cloudflare/src/framework/response/mod.rs

A number of services within our infrastructure do not include these fields if they are empty. Although the spec arguably mandates the inclusion of these keys, we should support what happens in the real world rather than what the spec recommends.

framework: support missing messages and/or errors in ApiSuccess

---

cloudflare/Cargo.toml

Less disruptive than https://github.com/cloudflare/cloudflare-rs/pull/200 but does fix the issue as long as no other dependency in a project depends on `chrono` with default features.

Remove time@0.1 transitive dep via chrono

---

cloudflare/Cargo.toml
cloudflare/src/framework/async_api.rs

`cfg-if` without a corresponding `else` isn't needed and just makes the build take longer. Let's get rid of it.

Remove unnecessary cfg-if dep

---

cloudflare-examples/Cargo.toml
cloudflare/Cargo.toml
cloudflare/src/framework/mod.rs
cloudflare/src/framework/response/mod.rs

This may not seem like a huge deal given that users need to build `tokio` anyway to use the library. But `blocking` is optional in `reqwest` because it adds to the list of required features for `tokio`, and so we should make it optional for consumers as well.

Make blocking API an optional feature

---

.github/workflows/lint.yml
.github/workflows/rust.yml
cloudflare-examples/src/main.rs
cloudflare/src/endpoints/cfd_tunnel/create_tunnel.rs
cloudflare/src/endpoints/cfd_tunnel/data_structures.rs
cloudflare/src/endpoints/cfd_tunnel/delete_tunnel.rs
cloudflare/src/endpoints/cfd_tunnel/list_tunnels.rs
cloudflare/src/endpoints/cfd_tunnel/mod.rs
cloudflare/src/endpoints/cfd_tunnel/route_dns.rs
cloudflare/src/endpoints/cfd_tunnel/update_tunnel.rs
cloudflare/src/endpoints/mod.rs
cloudflare/src/framework/endpoint.rs

Now that Argo Tunnel is a deprecated API, this commit adds support for Cfd Tunnels

Add support for Cfd Tunnels

---

cloudflare/Cargo.toml

Adding the repository in the Cargo.toml file will give greater accessability to this Crate's source code to its users.
Closes https://github.com/cloudflare/cloudflare-rs/issues/235

Add repository in Cargo.toml

---

cloudflare/src/endpoints/zone.rs

Does the following:
- Removes the `multiple_railguns_allowed` field, as it appears to be removed. Fixes #236
- Makes the fields of the `owner` field optional (#232), as otherwise the examples would still not work
- Adds the `activated_on` field
There are some more discrepancies, i.e. fields on the docs that don't exist here, and fields here that don't exist in the docs, but I want to refrain from changing too much. 
This can be tested with the `cloudflare-examples` cli:
<details>
<summary>Before</summary>
```
$ cargo run --bin cloudflare-examples -- --auth-token=XXX zone XXX
Compiling cloudflare v0.12.0 (/home/wp/programming/cloudflare-rs/cloudflare)
Compiling cloudflare-examples v0.6.0 (/home/wp/programming/cloudflare-rs/cloudflare-examples)
Finished dev [unoptimized + debuginfo] …
```

Update broken Zone entry struct

---

cloudflare/src/endpoints/dns.rs

As https://developers.cloudflare.com/changelog/ said on 27th, Jan, 2025, "Records returned by the API will no longer contain the zone_id and zone_name fields.", so we need to remove it to avoid parse error.
ref #251

fix(cloudflare): Remove `zone_id` and `zone_name` in DNSRecord

---

cloudflare/Cargo.toml
cloudflare/src/endpoints/ai/execute_model.rs
cloudflare/src/endpoints/ai/mod.rs
cloudflare/src/endpoints/mod.rs

This adds support for the execute model endpoint, as described here: https://developers.cloudflare.com/api/resources/ai/methods/run/
This also adds an optional feature `ndarray` that can deserialize embeddings directly into an `ndarray::ArrayD`.

ai: Support new (Workers) AI API endpoint

---

cloudflare/src/endpoints/workers/mod.rs

Currently the `WorkersBinding` assume that it always have `namespace_id` and also does not take into consideration all the other possible fields of different bindings.
This changes so that the `WorkerBinding` is now an enum with all the possible options listed on https://developers.cloudflare.com/workers/configuration/multipart-upload-metadata/#bindings.
Closes #261

feat: implement WorkersBinding as an enum 
